PS1='\w\$ '

export GREP_OPTIONS='--color=auto'
export PYTHONDONTWRITEBYTECODE=1

alias ls='ls -G'
alias ll='ls -l'
alias tree='tree -C'

GIT_PS1_SHOWDIRTYSTATE=true
export PS1='\w\[\033[36m\]$(__git_ps1 \(%s\))\[\033[00m\]\$ '
source /usr/local/etc/bash_completion.d/git-prompt.sh
source /usr/local/etc/bash_completion.d/git-completion.bash
