set textwidth=0
set nobackup
set autoread
set noswapfile
set hidden
set nowrap
set showcmd
set showmode
set smartcase
set ignorecase
set cmdheight=1
set laststatus=2

set number
set numberwidth=5
set showmatch
set matchtime=1
set cursorline
set ruler
set visualbell

set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set incsearch
set hlsearch
set nowrapscan
set ambiwidth=double
set tags+=.ctags/tags
set clipboard+=unnamed
set statusline=%<\ %f\ %m%r%{'['.(&fenc!=''?&fenc:&enc).']['.&ff.']'}%=%l/%L,%v

if has('mouse')
  set mouse=a
endif

if has('vim_starting')
  if &compatible
    set nocompatible
  endif
  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#begin(expand('~/.vim/bundle/'))

NeoBundleFetch 'Shougo/neobundle.vim'

NeoBundle 'Shougo/unite.vim'
NeoBundle 'Shougo/vimfiler.vim'
NeoBundle 'altercation/vim-colors-solarized'

call neobundle#end()

filetype on
filetype plugin indent on

NeoBundleCheck

let g:unite_enable_start_insert=1
let g:unite_source_history_yank_enable=1
let g:unite_source_file_mru_limit=200
let g:vimfiler_as_default_explorer=1
let g:solarized_bold=0

syntax on
set background=dark
colorscheme solarized

vnoremap * "zy:let @/=@z<CR>n

autocmd FileType make setlocal noexpandtab
autocmd FileType ruby setlocal tabstop=2 softtabstop=2 shiftwidth=2
autocmd FileType xml  setlocal tabstop=2 softtabstop=2 shiftwidth=2
autocmd BufNewFile,BufRead *.{md,mdwn,mdk,mkdn,mark*} set filetype=markdown

