set textwidth=0
set nobackup
set autoread
set noswapfile
set hidden
set nowrap
set showcmd
set showmode
set smartcase
set ignorecase
set laststatus=2
set clipboard+=unnamed

set number
set showmatch
set matchtime=1
set cursorline
set ruler
set visualbell

set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set incsearch
set hlsearch
set nowrapscan
set colorcolumn=100
set ambiwidth=double
set tags+=.ctags/tags
set backspace=indent,eol,start
set statusline=%<\ %f\ %m%r%{'['.(&fenc!=''?&fenc:&enc).']['.&ff.']'}%=%l/%L,%v

if has('mouse')
    set mouse=a
endif

if &compatible
    set nocompatible
endif

set runtimepath^=~/.cache/dein/repos/github.com/Shougo/dein.vim

call dein#begin(expand('~/.cache/dein'))
call dein#add('Shougo/dein.vim')
call dein#add('Shougo/unite.vim')
call dein#add('Shougo/vimfiler.vim')
call dein#add('nanotech/jellybeans.vim')
call dein#add('keith/swift.vim')
call dein#end()

if dein#check_install()
    call dein#install()
endif


syntax on
set background=dark
colorscheme jellybeans

let g:unite_enable_start_insert=1
let g:unite_source_history_yank_enable=1
let g:unite_source_file_mru_limit=200
let g:vimfiler_as_default_explorer=1

vnoremap * "zy:let @/=@z<CR>n

augroup file_type
    autocmd!
    filetype plugin on
    filetype indent on
    autocmd FileType make   setlocal noexpandtab
    autocmd FileType xml    setlocal tabstop=2 softtabstop=2 shiftwidth=2
    autocmd FileType json   setlocal tabstop=2 softtabstop=2 shiftwidth=2
    autocmd FileType ruby   setlocal tabstop=2 softtabstop=2 shiftwidth=2
    autocmd FileType swift  setlocal tabstop=2 softtabstop=2 shiftwidth=2
    autocmd FileType python setlocal completeopt-=preview
augroup END
