set ambiwidth=double
set autoread
set backspace=indent,eol,start
set clipboard+=unnamed
set colorcolumn=80
set cursorline
set expandtab
set hidden
set hlsearch
set ignorecase
set incsearch
set laststatus=2
set matchtime=1
set nobackup
set noerrorbells
set noswapfile
set nowrap
set nowrapscan
set number
set ruler
set shiftwidth=2
set showcmd
set showmatch
set showmode
set smartcase
set softtabstop=2
set tabstop=2
set textwidth=0
set t_md=

if has('mouse')
  set mouse=a
endif

if &compatible
  set nocompatible
endif

set runtimepath^=~/.cache/dein/repos/github.com/Shougo/dein.vim

call dein#begin(expand('~/.cache/dein'))
call dein#add('Shougo/dein.vim')
call dein#add('Shougo/unite.vim')
call dein#add('Shougo/vimfiler.vim')
call dein#add('justmao945/vim-clang')
call dein#add('keith/swift.vim')
call dein#add('nanotech/jellybeans.vim')
call dein#add('qpkorr/vim-bufkill')
call dein#add('vim-airline/vim-airline')
call dein#add('vim-airline/vim-airline-themes')
call dein#end()

if dein#check_install()
  call dein#install()
endif

syntax on
set background=dark
colorscheme jellybeans

let g:airline_powerline_fonts=1
let g:airline_theme='jellybeans'
let g:airline#extensions#tabline#enabled=1
let g:airline#extensions#tabline#buffer_idx_mode = 1
let g:clang_auto=0
let g:clang_c_completeopt='menuone'
let g:clang_c_options='-std=c14'
let g:clang_cpp_completeopt='menuone'
let g:clang_cpp_options='-std=c++14 -stdlib=libc++'
let g:clang_diagsopt=''
let g:clang_format_auto=1
let g:clang_format_exec='clang-format'
let g:clang_format_styke='Google'
let g:unite_enable_start_insert=1
let g:unite_source_history_yank_enable=1
let g:unite_source_file_mru_limit=200
let g:vimfiler_as_default_explorer=1

nmap <leader>1 <Plug>AirlineSelectTab1
nmap <leader>2 <Plug>AirlineSelectTab2
nmap <leader>3 <Plug>AirlineSelectTab3
nmap <leader>4 <Plug>AirlineSelectTab4
nmap <leader>5 <Plug>AirlineSelectTab5
nmap <leader>6 <Plug>AirlineSelectTab6
nmap <leader>7 <Plug>AirlineSelectTab7
nmap <leader>8 <Plug>AirlineSelectTab8
nmap <leader>9 <Plug>AirlineSelectTab9
nmap <leader>- <Plug>AirlineSelectPrevTab
nmap <leader>+ <Plug>AirlineSelectNextTab

vnoremap * "zy:let @/=@z<CR>n

augroup file_type
  autocmd!
  filetype plugin on
  filetype indent on
  autocmd FileType make setlocal noexpandtab tabstop=4 softtabstop=4 shiftwidth=4
  autocmd FileType cpp inoremap <silent> <C-n> <C-x><C-o><C-p>
augroup END
